name: irongrid_app
description: IronGrid App

environment:
  sdk: ">=3.0.0 <4.0.0"
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.2.2
  flutter_vlc_player: ^7.4.4
  url_launcher: ^6.3.1

  # Storage & Security
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # Device features
  local_auth: ^2.3.0
  image_picker: ^1.0.7
  path_provider: ^2.1.5

  # Charts
  fl_chart: ^0.68.0

dependency_overrides:
  objective_c: 9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
